SELECT C.ID, C.FULL_NAME, C.CPF_CNPJ, C.CLIENT_STATUS_ID, STA.NAME, C.CLIENT_CLASSIFICATION_ID, CLA.NAME, E.ADDRESS, C.ADVISOR_ID, A.EMAIL FROM CLIENT AS C
INNER JOIN CLIENT_STATUS AS STA ON C.CLIENT_STATUS_ID = STA.ID
INNER JOIN CLIENT_CLASSIFICATION AS CLA ON C.CLIENT_CLASSIFICATION_ID = CLA.ID
INNER JOIN EMAIL AS E ON C.ID = E.CLIENT_ID
INNER JOIN ADVISOR AS A ON C.ADVISOR_ID = A.ID
--WHERE C.FULL_NAME LIKE '%felipe PI%' 
